
const PAGE_INIT 			    = "PAGE_INIT";
const PAGE_ERROR 			    = "PAGE_ERROR";

const QUERY_TYPE_PAGE 			= "QUERY_TYPE_PAGE";
const QUERY_TYPE_UNKNOWN 		= "QUERY_TYPE_UNKNOWN";

const ACTION_TYPE_PAGE_LOAD 	= "ACTION_TYPE_PAGE_LOAD";
const ACTION_TYPE_QUERY_OPEN 	= "ACTION_TYPE_QUERY_OPEN";
const ACTION_TYPE_QUERY_CLOSE 	= "ACTION_TYPE_QUERY_CLOSE";
const ACTION_TYPE_PAGE_REDIRECT = "ACTION_TYPE_PAGE_REDIRECT";

const ANSWER_TYPE_PAGE 			= "PAGE";
const ANSWER_TYPE_ERROR			= "ERROR";
const ANSWER_TYPE_REDIRECT		= "REDIRECT";

export {
	PAGE_INIT,
	PAGE_ERROR,
	QUERY_TYPE_PAGE,
	QUERY_TYPE_UNKNOWN,
	ACTION_TYPE_PAGE_LOAD,
	ACTION_TYPE_QUERY_OPEN,
	ACTION_TYPE_QUERY_CLOSE,
	ACTION_TYPE_PAGE_REDIRECT,
	ANSWER_TYPE_PAGE,
	ANSWER_TYPE_ERROR,
	ANSWER_TYPE_REDIRECT
};